name: 'mermaidjs-action'
description: 'Render mermaid diagrams'
inputs:
  input:
    description: 'Input mermaid file. Files ending in .md will be treated as Markdown and all charts (e.g. ```mermaid (...)```) will be extracted and generated.'
    required: false
    default: '**/*.md'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "--input ${{ inputs.input }}"
