name: 'mermaidjs-action'
description: 'Render mermaid diagrams'
inputs:
  files:
    description: 'Input mermaid file. Files ending in .md will be treated as Markdown and all charts (e.g. ```mermaid (...)```) will be extracted and generated.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file_pattern }}
