name: 'mermaidjs-action'
description: 'Render mermaid diagrams'
inputs:
  file_pattern:
    description: 'File pattern for input files'
    required: false
    default: '**/*.md'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file_pattern }}
