name: Tests
on: push

jobs:
  render-mermaidjs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Render mermaid diagrams
      uses: ./
      with:
        input: 'examples.md'
        output: 'img/examples.svg'
